name: Python CI - System Monitor

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  send_email:
    runs-on: ubuntu-latest


    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest tests/
        env:
          SENDER_EMAIL: ${{ secrets.SEND_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SEND_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIV_EMAIL }}

      - name: "Run app.py script"
        run: python app/app.py
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          SENDER_EMAIL: ${{ secrets.SEND_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SEND_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIV_EMAIL }}

      - name: Check application logs
        if: always()
        run: |
            echo "Workflow completed"
            echo "Check above logs for any errors"
